import Head from "next/head";
import Image from "next/image";

import Hero from "../components/Hero";
import Model3 from "../components/Model3";
import ModelX from "../components/ModelX";


export default function Home() {
  return (
    <>
      <Head>
        <title>Electric cars and solar energy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <img src="https://digitalassets.tesla.com/tesla-contents/image/upload/f_auto,q_auto/Homepage-Model-Y-Desktop-Global.png" alt="bg-img" className="relative h-screen w-full object-cover" />
      {/* <Navbar />
      <Model3 />
      <ModelX /> */}
       <Hero />
       < Model3 />
       <ModelX />
      
      
    </>
  );
}
